#!/bin/sh

set -e

TESTSUITE_DIR=/$($(dirname $0)/../rules echo-MOZ_LIBDIR 2>/dev/null)/testing
TESTRESULTS_DIR=${ADTRESULTSDIR:-"/tmp/testresults"}

$TESTSUITE_DIR/filter_results -d $TESTRESULTS_DIR -m $(dirname $0)/../testing/results-filter-manifest.json
