#!/usr/bin/env ruby

require 'drb/drb'

require_relative 'lib/semaphore'
require_relative 'lib/service'

URI = Service::SERVER_URI
FRONT_OBJECT = Semaphore.new

DRb.start_service(URI, FRONT_OBJECT)
DRb.thread.join
