#!/usr/bin/env ruby
# frozen_string_literal: true
# SPDX-FileCopyrightText: 2021 Harald Sitter <sitter@kde.org>
# SPDX-License-Identifier: LGPL-2.1-only OR LGPL-3.0-only OR LicenseRef-KDE-Accepted-LGPL

require_relative 'lib/paths' # Drop the overlay from the PATH env.

if ENV['PANGEA_UNDER_TEST']
  ARGV.reject! { |arg| arg.start_with?('-Z', '-S') }
  ARGV.prepend('-Znone', '-Snone')
  puts "Removing compression from deb; new ARGV #{ARGV}"
end

exec('dpkg-deb', *ARGV)
