#!/usr/bin/env ruby
#
# frozen_string_literal: true
#
# Copyright (C) 2018 Harald Sitter <sitter@kde.org>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) version 3, or any
# later version accepted by the membership of KDE e.V. (or its
# successor approved by the membership of KDE e.V.), which shall
# act as a proxy defined in Section 6 of version 3 of the license.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library.  If not, see <http://www.gnu.org/licenses/>.

require_relative 'lib/paths' # Drop the overlay from the PATH env.

# Force parallel xz. Be careful with this overlay, depending on what is running
# while the overlay is active this may be breaking things (e.g. initramfs cannot
# be parallel compressed as the decompressor won't know how to uncompress).
# Because of this you need to explicitly opt into this overlay!
cmd = ENV['OVERLAY_PARALLEL_COMPRESSION'] ? :pxz : :xz
if cmd == :pxz && !system('which pxz')
  warn 'Cannot use parallel compression because pxz is missing'
  cmd = :xz
end
exec(cmd, *ARGV)
