#!/usr/bin/env ruby

require 'fileutils'

if ARGV.include?('adt-run.XXXXXX')
  FileUtils.rm_rf('/workspace')
  FileUtils.mkpath('/workspace')
  puts '/workspace'
  exit 0
end

system('/bin/mktemp', *ARGV)
exit $?.to_i
