#!/bin/sh

set -e

TESTSUITE_DIR=/$($(dirname $0)/../rules echo-MOZ_LIBDIR 2>/dev/null)/testing
TESTRESULTS_DIR=${ADTRESULTSDIR:-"/tmp/testresults"}

export LC_ALL=en_US.UTF-8

mkdir -p $TESTRESULTS_DIR

$TESTSUITE_DIR/run_mochitest --own-session --xunit-file $TESTRESULTS_DIR/mochitest-plain-1.xml --chunk-by-dir 4 --total-chunks 5 --this-chunk 1 --xunit-name 'mochitest.plain.1'
