#!/bin/sh

set -e

TESTSUITE_DIR=/$($(dirname $0)/../rules echo-MOZ_LIBDIR 2>/dev/null)/testing
TESTRESULTS_DIR=${ADTRESULTSDIR:-"/tmp/testresults"}

export LC_ALL=en_US.UTF-8

mkdir -p $TESTRESULTS_DIR

$TESTSUITE_DIR/run_mochitest --own-session --xunit-file $TESTRESULTS_DIR/mochitest-ipcplugins.xml --xunit-name "mochitest.ipcplugins" --setpref=dom.ipc.plugins.enabled=false --test-path=dom/plugins/test
