#!/bin/bash

# (C) 2012-2015 Fathi Boudra <fathi.boudra@linaro.org>
# (C) 2015 Rohan Garg <rohan@garg.io>
# (C) 2017 Jonathan Riddell <jr@jriddell.org>
# May be copied under the terms of the GNU GPL version 3 only

# Create configuration for live-build.

# You need live-build package installed.

set -e
set -x

echo "I: create configuration"

SNAP_URL='http://ports.ubuntu.com/ubuntu-ports/'

export LB_HDD_PARTITION_START="40960s"
export LB_BOOTLOADERS="none"
export LB_HDD_LABEL="PINEBOOKneon"
export LB_MKFS_OPTIONS="-O ^64bit,^metadata_csum,uninit_bg"

. /etc/os-release

### HACK: super ugly hack for getting usable bionic image
if [ "$VERSION_CODENAME" = "bionic" ]; then
    sed -i 's/64bit/64bit,\^metadata_csum,uninit_bg/' /usr/lib/live/build/binary_hdd
fi

env

lb config \
 --architectures arm64 \
 --archive-areas 'main universe' \
 --apt-options "--yes --allow-downgrades" \
 --bootstrap-qemu-arch arm64 --bootstrap-qemu-static /usr/bin/qemu-aarch64-static \
 --cache false \
 --cache-indices false \
 --cache-packages false \
 --cache-stages 'none' \
 --distribution $DIST \
 --binary-images hdd \
 --mode ubuntu \
 --debootstrap-options='--include="gnupg,ca-certificates"' \
 --apt-source-archives false \
 --source true \
 --apt-options "--yes -o Acquire::Check-Valid-Until=false" \
 --linux-flavours none \
 --linux-packages none \
 --initramfs none \
 --chroot-filesystem none \
 --binary-filesystem ext4 \
 --hdd-size 6000 \
 --firmware-chroot false \
 --security false \
 -m $SNAP_URL \
 --parent-mirror-binary $SNAP_URL \
 --mirror-bootstrap $SNAP_URL \
 --mirror-chroot $SNAP_URL \
 --mirror-binary $SNAP_URL \
 --mirror-debian-installer $SNAP_URL \
 $@

echo "I: copy customization"
test -d /tooling/nci/imager-img/customization && cp -rf /tooling/nci/imager-img/customization/* config/


if [ "$VERSION_CODENAME" = "bionic" ]; then
    echo "W: removing some packages which are not built for bionic yet"
    sed -i '/ksystraycmd5/d' config/package-lists/neon.list.chroot
    sed -i '/libcedrus1/d' config/package-lists/neon.list.chroot
    sed -i '/libvdpau-sunxi1/d' config/package-lists/neon.list.chroot
    sed -i '/mpv/d' config/package-lists/neon.list.chroot
    sed -i '/smplayer/d' config/package-lists/neon.list.chroot

    # upadte hook to use prebuilt packages
    rm config/hooks/live/live-config.hook.chroot
    echo 'live-config' >> config/package-lists/neon.list.chroot
    echo 'live-config-systemd' >> config/package-lists/neon.list.chroot

    # remove the double sddm hook
    mv config/includes.chroot/lib/live/config/0090-sddm config/includes.chroot/lib/live/config/0085-sddm
fi

echo "I: done"
