#!/bin/bash

# (C) 2012-2015 Fathi Boudra <fathi.boudra@linaro.org>
# (C) 2015 Rohan Garg <rohan@garg.io>
# (C) 2017 Jonathan Riddell <jr@jriddell.org>
# May be copied under the terms of the GNU GPL version 3 only

# Create configuration for live-build.

# You need live-build package installed.

set -e
set -x

echo "I: create configuration"

SNAP_URL='http://ports.ubuntu.com/ubuntu-ports/'

export LB_HDD_PARTITION_START="40960s"
export LB_BOOTLOADERS="none"
export LB_HDD_LABEL="PINEBOOKneon"
export LB_MKFS_OPTIONS="-O ^64bit,^metadata_csum,uninit_bg"

env

lb config \
 --architectures arm64 \
 --archive-areas 'main universe' \
 --apt-options "--yes --allow-downgrades" \
 --bootstrap-qemu-arch arm64 --bootstrap-qemu-static /usr/bin/qemu-aarch64-static \
 --cache false \
 --cache-indices false \
 --cache-packages false \
 --cache-stages 'none' \
 --distribution $DIST \
 --binary-images hdd \
 --mode ubuntu \
 --apt-source-archives false \
 --source false \
 --apt-options "--yes -o Debug::pkgProblemResolver=true -o Debug::pkgDepCache::AutoInstall=true -o Debug::pkgDepCache::Marker=true -o Acquire::Check-Valid-Until=false" \
 --linux-flavours none \
 --linux-packages none \
 --initramfs none \
 --chroot-filesystem none \
 --binary-filesystem ext4 \
 --hdd-size 6000 \
 --firmware-chroot false \
 --security false \
 -m $SNAP_URL \
 --parent-mirror-binary $SNAP_URL \
 --mirror-bootstrap $SNAP_URL \
 --mirror-chroot $SNAP_URL \
 --mirror-binary $SNAP_URL \
 --mirror-debian-installer $SNAP_URL \
 $@

echo "I: copy customization"
test -d /tooling/nci/imager-img/customization && cp -rf /tooling/nci/imager-img/customization/* config/

mkdir -p $HOME/.gnupg/

# use gnupg1 for bionic
. /etc/os-release

GPG="gpg"
ARGS=""

if [ "$VERSION_CODENAME" = "bionic" ]; then
  apt install -y dirmngr gnupg1
  ARGS="--batch --verbose"
  GPG="gpg1"
fi

$GPG --no-default-keyring \
  --primary-keyring config/archives/ubuntu-defaults.key \
  --keyserver keyserver.ubuntu.com \
  --recv-keys '444D ABCF 3667 D028 3F89  4EDD E6D4 7362 5575 1E5D'

$GPG --no-default-keyring \
  --primary-keyring config/archives/ubuntu-defaults.key \
  --keyserver keyserver.ubuntu.com \
  --recv-keys 'E47F 5011 FA60 FC1D EBB1  9989 3305 6FA1 4AD3 A421'

echo "I: done"
