#!/bin/sh

## live-config(7) - System Configuration Components
## Copyright (C) 2006-2015 Daniel Baumann <mail@daniel-baumann.ch>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


#set -e

Cmdline ()
{
	# Reading kernel command line
	for _PARAMETER in ${LIVE_CONFIG_CMDLINE}
	do
		case "${_PARAMETER}" in
			live-config.debug|debug)
				LIVE_CONFIG_DEBUG="true"
				;;

			live-config.noautologin|noautologin)
				LIVE_CONFIG_NOAUTOLOGIN="true"
				;;

			live-config.nottyautologin|nottyautologin)
				LIVE_CONFIG_NOTTYAUTOLOGIN="true"
				;;

			live-config.username=*|username=*)
				LIVE_USERNAME="${_PARAMETER#*username=}"
				;;
		esac
	done
}

Init ()
{
	# Disables both console and graphical autologin.
	case "${LIVE_CONFIG_NOAUTOLOGIN}" in
		true)
			exit 0
			;;
	esac

	# Disables console autologin, no matter what mechanism
	case "${LIVE_CONFIG_NOTTYAUTOLOGIN}" in
		true)
			exit 0
			;;
	esac

	# Checking if package is installed or already configured
	if [ ! -e /var/lib/dpkg/info/systemd.list ] || \
	   [ -e /var/lib/live/config/systemd ]
	then
		exit 0
	fi

	echo -n " systemd"
}

Config ()
{
	# Configure autologin
	if [ -n "${LIVE_USERNAME}" ]
	then
		for NUMBER in $(seq 1 6)
		do
			mkdir -p /etc/systemd/system/getty@tty${NUMBER}.service.d

cat > /etc/systemd/system/getty@tty${NUMBER}.service.d/live-config_autologin.conf << EOF
[Service]
Type=idle
ExecStart=
ExecStart=-/sbin/agetty --autologin ${LIVE_USERNAME} --noclear %I \$TERM
EOF

			case "${LIVE_CONFIG_DEBUG}" in
				true)
					echo "TTYVTDisallocate=no" >> /etc/systemd/system/getty@tty${NUMBER}.service.d/live-config_autologin.conf
					;;
			esac
		done

		for NUMBER in $(seq 1 6)
		do
			systemctl --no-block daemon-reload
			systemctl --no-block restart getty@tty${NUMBER}.service
		done
	fi

	# Creating state file
	touch /var/lib/live/config/systemd
}

Cmdline
Init
Config
