#!/bin/sh

set -e

TESTSUITE_DIR=/$($(dirname $0)/../rules echo-MOZ_LIBDIR 2>/dev/null)/testing
TESTRESULTS_DIR=${ADTRESULTSDIR:-"/tmp/testresults"}

export LC_ALL=en_US.UTF-8

mkdir -p $TESTRESULTS_DIR
$TESTSUITE_DIR/run_reftest --own-session --xunit-file $TESTRESULTS_DIR/crashtest.xml --xunit-name "crashtest" reftest/tests/testing/crashtest/crashtests.list
