#!/bin/sh

set -e

TESTSUITE_DIR=/$($(dirname $0)/../rules echo-MOZ_LIBDIR 2>/dev/null)/testing
TESTRESULTS_DIR=${ADTRESULTSDIR:-"/tmp/testresults"}

export LC_ALL=en_US.UTF-8

# Required for js/src/trace-tests/sunspider/check-date-format-tofte.js
export TZ=:/usr/share/zoneinfo/posix/US/Pacific

mkdir -p $TESTRESULTS_DIR
$TESTSUITE_DIR/run_reftest --own-session --xunit-file $TESTRESULTS_DIR/jstestbrowser.xml --xunit-name "jstestbrowser" --tests-root-dir jsreftest/tests --extra-profile-file=jsreftest/tests/user.js jsreftest/tests/jstests.list
