# konsole needs installed first else xterm gets installed cos xorg deps on
# terminal | xterm and doesn't know terminal is installed later in the tree
cat << EOF > config/package-lists/ubuntu-defaults.list.chroot_install
konsole
plasma-minishell
mycroft-gui
mycroft-core
mycroft-skill-installer
mycroft-settings
breeze
fonts-hack-ttf
fonts-noto-hinted
konsole
kde-cli-tools
khotkeys
kio-extras
kwin
libsasl2-modules
libu2f-udev
neon-hardware-integration
neon-keyring
neon-settings
oxygen-sounds
plasma-nm
plasma-pa
plasma-workspace-wallpapers
plasma-workspace-wayland
pm-utils
powerdevil
sddm
sddm-theme-breeze
software-properties-common
systemsettings
ubuntu-drivers-common
unzip
wireless-tools
wpasupplicant
xdg-user-dirs
xkb-data
xorg
xserver-xorg-video-intel-arbiter
xserver-xorg-input-evdev
xserver-xorg-input-synaptics
xserver-xorg-video-intel-native-modesetting
zip
EOF
